
# Output
basecalled_fastq = "/staging/leuven/stg_00096/home/dkresa/data/bulk/1694205563_gc-run-230905-promethion1-fc1d/basecalled/bam/1694205563_basecalled.bam"


rule all:
    input:
        basecalled_fastq

# Rule for basecalling in dorado (pod5 -> fastq)
rule dorado_basecall:
    input:
        pod5 = "/staging/leuven/stg_00096/home/dkresa/ResolveOME/bulk/1694205563_gc-run-230905-promethion1-fc1d/pod5_pass/"
    output:
        bam = "/staging/leuven/stg_00096/home/dkresa/data/bulk/1694205563_gc-run-230905-promethion1-fc1d/basecalled/bam/1694205563_basecalled.bam"
    threads: 24
    shell:
        """
        singularity run --nv -B /staging/leuven/stg_00096/home/dkresa \
        -B /lustre1/project/stg_00096/data/2023_ResolveOME_RPMI4802/bulk/1694205563_gc-run-230905-promethion1-fc1d \
        /staging/leuven/stg_00096/home/dkresa/singularity/dorado_v0.4.1.sif \
        /opt/dorado/bin/dorado basecaller /opt/dorado/bin/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 {input.pod5} > {output.bam}
        """
