# Define paths to references
reference = "/lustre1/project/stg_00096/references/GRCh38.alt-masked-V2/index/bwa-mem2/Homo_sapiens_assembly38_masked.fasta"
pod5_dir = "/staging/leuven/stg_00096/home/dkresa/ResolveOME/bulk/1694205563_gc-run-230905-promethion1-fc1d/pod5_pass/"
dorado_dir = "/staging/leuven/stg_00096/home/dkresa/singularity/dorado_v0.4.1.sif"
stage_dir = "/staging/leuven/stg_00096"
lustre_dir = "/lustre1/project/stg_00096"

# Define output files
dorado_basecaller_output = "basecalled/bam/1694205563_basecalled_aligned.bam"
dorado_summary_output = "basecalled/summary/sequencing_summary.tsv"
dorado_demux_output = "basecalled/demux/"

#Define output reports
dorado_basecaller_report = "reports/dorado_basecaller/1694205563_basecalled_aligned.txt"
dorado_summary_report = "reports/dorado_summary/sequencing_summary.txt"
dorado_demux_report = "reports/dorado_demux/1694205563_basecalled_aligned.txt"


rule all:
    input:
        dorado_basecaller_output,
        dorado_basecaller_report,
        dorado_summary_output,
        dorado_summary_report,
        dorado_demux_output,
        dorado_demux_report


# Rule for basecalling in dorado
rule dorado_basecaller:
    input:
        pod5 = pod5_dir,
        ref = reference
    output:
        bam = "basecalled/bam/1694205563_basecalled_aligned.bam",
        task_done = "reports/dorado_basecaller/1694205563_basecalled_aligned.txt"
    params:
        stage = stage_dir,
        lustre = lustre_dir,
        dorado = dorado_dir
    threads: 24
    shell:
        """
        singularity run --nv \
        -B {params.stage} \
        -B {params.lustre} \
        {params.dorado} \
        /opt/dorado/bin/dorado basecaller \
        /opt/dorado/bin/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 {input.pod5} \
        --kit-name SQK-NBD114-24 \
        --reference {input.ref} \
        -k14 \
        -w 10 \
        --secondary no \
        > {output.bam}

        touch {output.task_done}
        """

# Rule for sequencing summary
rule dorado_summary:
    input:
        bam = "basecalled/bam/1694205563_basecalled_aligned.bam",
        check_input = dorado_basecaller_report
    output:
        summary = "basecalled/summary/sequencing_summary.tsv",
        task_done = "reports/dorado_summary/sequencing_summary.txt"
    params:
        stage = stage_dir,
        lustre = lustre_dir,
        dorado = dorado_dir
    threads: 24
    shell:
        """
        singularity run --nv \
        -B {params.stage} \
        -B {params.lustre} \
        {params.dorado} \
        /opt/dorado/bin/dorado summary \
        {input.bam} \
        > {output.summary}

        touch {output.task_done}
        """

# Rule for demultiplexing/barcode classification in dorado
rule dorado_demux:
    input:
        bam = "basecalled/bam/1694205563_basecalled_aligned.bam",
        check_input = dorado_summary_report
    output:
        demux = "basecalled/demux/",
        task_done = "reports/dorado_demux/1694205563_basecalled_aligned.txt"
    params:
        stage = stage_dir,
        lustre = lustre_dir,
        dorado = dorado_dir
    threads: 24
    log:
       out = "logs/dorado_demux/1694205563_basecalled_aligned.out",
       err = "logs/dorado_demux/1694205563_basecalled_aligned.err"
    shell:
        """
        singularity run --nv \
        -B {params.stage} \
        -B {params.lustre} \
        {params.dorado} \
        /opt/dorado/bin/dorado demux \
        --output-dir {output.demux} \
        --no-classify {input.bam} \
        1> {log.out} 2> {log.err}

        touch {output.task_done}
        """

