# Define reference genome path
reference = "/lustre1/project/stg_00096/references/GRCh38.alt-masked-V2/index/bwa-mem2/Homo_sapiens_assembly38_masked.fasta"

# Define samples using glob_wildcards
samplesR, = glob_wildcards("/staging/leuven/stg_00096/home/dkresa/ResolveOME/bulk/230810_RPMI8402_Illumina_seq/230825.NovaSeq2.FCA/1399/{sampleR}.fastq.gz")

# Filter samples to exclude those with "I1" or "I2" in their names
samplesR = [sampleR for sampleR in samplesR if "I1" not in sampleR and "I2" not in sampleR]

# Define samples using glob_wildcards
samples_R1, = glob_wildcards("/staging/leuven/stg_00096/home/dkresa/ResolveOME/bulk/230810_RPMI8402_Illumina_seq/230825.NovaSeq2.FCA/1399/{sample}_R1_001.fastq.gz")
samples_R2, = glob_wildcards("/staging/leuven/stg_00096/home/dkresa/ResolveOME/bulk/230810_RPMI8402_Illumina_seq/230825.NovaSeq2.FCA/1399/{sample}_R2_001.fastq.gz")

# List all the FastQC output files without wildcards
fastqc_output_files = expand("/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/QC/1_premap/{sampleR}_fastqc.zip", sampleR=samplesR)

multiqc_report = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/QC/1_premap/multiqc_report.html"

# List all the BWA MEM output BAM files without wildcards
bwa_output_bam_files = expand("/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.bam", sample=samples_R1)

# List all the samtools output bai files without wildcards
samtools_output_bai_files = expand("/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.sorted.bam.bai", sample=samples_R1)


rule all:
    input:
        fastqc_output_files,
        multiqc_report,
        bwa_output_bam_files,
        samtools_output_bai_files

# Rule for quality control (FastQC):
rule fastqc:
    input:
        fq = "/staging/leuven/stg_00096/home/dkresa/ResolveOME/bulk/230810_RPMI8402_Illumina_seq/230825.NovaSeq2.FCA/1399/{sampleR}.fastq.gz"
    output:
        zip = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/QC/1_premap/{sampleR}_fastqc.zip",
        html = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/QC/1_premap/{sampleR}_fastqc.html"
    threads: 24
    shell:
        """
        echo "Input Fastq: {input.fq}"
        fastqc -o /staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/QC/1_premap {input.fq} 
        """

# Rule for generating MultiQC report
rule multiqc:
    input:
        report_files = fastqc_output_files
    output:
        html_report = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/QC/1_premap/multiqc_report.html"
    threads: 24
    shell:
        """
        echo "Input Multiqc: {input.report_files}"
        multiqc -f -o /staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/QC/1_premap {input.report_files}
        """

# Rule for running BWA MEM2 alignment
rule bwa_mem2:
    input:
        report_files = multiqc_report,
        fq1 = "/staging/leuven/stg_00096/home/dkresa/ResolveOME/bulk/230810_RPMI8402_Illumina_seq/230825.NovaSeq2.FCA/1399/{sample}_R1_001.fastq.gz",
        fq2 = "/staging/leuven/stg_00096/home/dkresa/ResolveOME/bulk/230810_RPMI8402_Illumina_seq/230825.NovaSeq2.FCA/1399/{sample}_R2_001.fastq.gz",
        ref = reference
    threads: 24    
    output:
        bam = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.bam",
    shell:
        """
        /lustre1/project/stg_00096/software/bwa-mem2-2.2.1_x64-linux/bwa-mem2 mem -t {threads} {input.ref} {input.fq1} {input.fq2} | samtools view -Sb -> {output.bam}
        """

# Rule for sorting and indexing BAM files
rule sort_and_index:
    input:
        bam = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.bam"
    output:
        sorted_bam = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.sorted.bam",
        bam_index = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.sorted.bam.bai"
    threads: 24
    shell:
        """
        samtools sort -@ {threads} -o {output.sorted_bam} {input.bam}
        samtools index {output.sorted_bam} {output.bam_index}
        """

# Rule for marking duplicates using sambamba markdup
rule mark_duplicates:
    input:
        merged_bam = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.sorted.bam"
    output:
        merged_bam_markdup = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.sorted_markdup.bam",
        merged_bam_markdup_index = "/staging/leuven/stg_00096/home/dkresa/data/bulk/230810_RPMI8402_Illumina_seq/bwa/{sample}.sorted_markdup.bam.bai"
    threads: 24
    shell:
        """
        sambamba markdup -p --nthreads {threads} {input.merged_bam} {output.merged_bam_markdup}
        samtools index {output.merged_bam_markdup} {output.merged_bam_markdup_index}
        """